### ISSUE TITLE
Usage of Wire.requestFrom() and Wire.available().

### ISSUE THREAD

**Issue by Koepel** [giljr/Ardu_Serie#1]
The Wire.beginTransmission() and Wire.endTransmission() are only used when writing data. They should not be used with Wire.requestFrom().
The Wire.requestFrom() does a complete I2C transaction on its own, and when it returns the I2C transaction has completely finished and the received data is waiting in a buffer in the Wire library. The Wire.available() tells how many bytes are in that buffer.

In the next files, the Wire.requestFrom() is encapsulated by Wire.beginTransmission() and Wire.endTransmission(). You can remove those Wire.beginTransmission() and Wire.endTransmission().
- _35_GY85__ITG3205_Gyroscope_07.ino
- _35_GY85_ADXL354_Accelerometer_06.ino

When requesting a single byte, and testing it with: `if (Wire.available() <= 1)`, then it is **always** true. When there was a problem on the I2C bus and the Wire library could detect it, then Wire.available() would probably return zero. If everything was okay, the Wire.available() would return the same number as requested.

Therefor, all those `if (Wire.available() <= ?)` can be removed. It is used in the files:
- _34_gyroscope_code.ino
- _34_magnetometer_code.ino
- _35_GY85_HMC5883L_Magnetometer_08.ino
- _24_arduSerie_Arduino_Compass.ino
- _24_arduSerie_Arduino_Bluetooth_Compass.ino
- _34_accelerometer_code.ino
- _34_Sensor_ADXL345_Template.ino

**Comment by giljr** [comment]
Perfect, Koepel! Thank you very much for your comments. I made the changes immediately after reading your instructions. They are really relevant. If possible, please check the changes :) Thank you again!

**Comment by Koepel** [comment]
I have checked the 9 changed files for the use of Wire.requestFrom() and it is okay.

**Comment by giljr** [comment]
I just wanted to say THANK YOU!

**Comment by giljr** [comment]
Solved.
